====================================
Iteration: 1
====================================
/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py:1339: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use and modify the model generation configuration (see https://huggingface.co/docs/transformers/generation_strategies#default-text-generation-configuration )
  warnings.warn(
Finished getting adversarial prompts.
OpenAIError encountered: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
OpenAIError encountered: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
Traceback (most recent call last):
  File "/project/language_models.py", line 106, in generate
    client = AzureOpenAI(
  File "/opt/conda/lib/python3.10/site-packages/openai/lib/azure.py", line 167, in __init__
    raise OpenAIError(
openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/project/main.py", line 188, in <module>
    main(args)
  File "/project/main.py", line 46, in main
    target_response_list = targetLM.get_response(adv_prompt_list)
  File "/project/conversers.py", line 163, in get_response
    outputs_list = self.model.batched_generate(full_prompts,
  File "/project/language_models.py", line 154, in batched_generate
    return [self.generate(conv, max_n_tokens, temperature, top_p) for conv in convs_list]
  File "/project/language_models.py", line 154, in <listcomp>
    return [self.generate(conv, max_n_tokens, temperature, top_p) for conv in convs_list]
  File "/project/language_models.py", line 142, in generate
    time.sleep(self.API_RETRY_SLEEP)
KeyboardInterrupt
Traceback (most recent call last):
  File "/project/language_models.py", line 106, in generate
    client = AzureOpenAI(
  File "/opt/conda/lib/python3.10/site-packages/openai/lib/azure.py", line 167, in __init__
    raise OpenAIError(
openai.OpenAIError: Missing credentials. Please pass one of `api_key`, `azure_ad_token`, `azure_ad_token_provider`, or the `AZURE_OPENAI_API_KEY` or `AZURE_OPENAI_AD_TOKEN` environment variables.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/project/main.py", line 188, in <module>
    main(args)
  File "/project/main.py", line 46, in main
    target_response_list = targetLM.get_response(adv_prompt_list)
  File "/project/conversers.py", line 163, in get_response
    outputs_list = self.model.batched_generate(full_prompts,
  File "/project/language_models.py", line 154, in batched_generate
    return [self.generate(conv, max_n_tokens, temperature, top_p) for conv in convs_list]
  File "/project/language_models.py", line 154, in <listcomp>
    return [self.generate(conv, max_n_tokens, temperature, top_p) for conv in convs_list]
  File "/project/language_models.py", line 142, in generate
    time.sleep(self.API_RETRY_SLEEP)
KeyboardInterrupt